## Lab 2

### Data Collection and Pre-Processing Lab Assignment

`Overview`

 Execute the 12-step Data Engineering road-map practiced in class, this time end-to-end on a realistic e-commerce dataset.

- Import the necessary libraries to be used

In [1]:
# import all the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Step 1 : Load the data from the csv and load the first 3 rows

In [59]:
# 
sales_df = pd.read_csv("../data/1000 Sales Records.csv")

sales_df = sales_df.head(500)


print("The number of rows", len(sales_df))
sales_df.head(3)

The number of rows 500

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62

## Step 2 Pick the Right Container

In [ ]:
# justify dict vs namedtuple vs sets

"""
We use a dict when you need key-value mapping. A namedtuple is ideal  immutable records with named fields. 
A set is used when you need to store unique items an such as filtering valid cities or deduplicating coupon codes.
"""

## Step 3 Implement Functions and Data Structure

In [3]:
sales_df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

Must contain: date, customer_id, product, price, quantity, coupon_code (or promo field), shipping_city


- the dataset does not have Customer_id, Coupon_code/Promo_code

#### Add the missing columns to the main dataset

In [4]:
import sys
import random
sys.path.append("../src") 

from generate_data import GenerateData

# instantiate the data
data_generator = GenerateData()

# print("Coupon Code:", data_generator.generate_coupon_codes())

methods = [method for method in dir(GenerateData) 
           if callable(getattr(GenerateData, method)) and not method.startswith("__")]

print("Methods in GenerateData:", methods)

Methods in GenerateData: ['generate_coupon_codes', 'generate_dataid']

In [5]:
# Apply to a DataFrame
# sales_df['Customer_ID'] = [data_generator.generate_dataid() for _ in range(len(sales_df))]
sales_df['Coupon_code'] = [data_generator.generate_coupon_codes() for _ in range(len(sales_df))]

# check of all columns
sales_df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Coupon_code
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02,9GVAC4W9I6XA82G
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34,LDOZZNQ0H63HALO
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62,71WUUHO4FEGOTT3
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98,B8IXDM1PVRRGQHH
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45,Q6F2E0ISEHTO91O

In [6]:

# add the customer id 
def generate_customer_ids(prefix="AX"):
        customer = f"{prefix}{random.randint(100000, 200000)}"
        return customer
    
sales_df['Customer_ID'] = [generate_customer_ids() for _ in range(len(sales_df))]
# check of all columns
sales_df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Coupon_code,Customer_ID
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02,9GVAC4W9I6XA82G,AX157377
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34,LDOZZNQ0H63HALO,AX186432
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62,71WUUHO4FEGOTT3,AX196913
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98,B8IXDM1PVRRGQHH,AX199663
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45,Q6F2E0ISEHTO91O,AX197093

In [7]:
sales_df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit',
       'Coupon_code', 'Customer_ID'],
      dtype='object')

In [8]:
# check for missing values
missing_values = sales_df.isnull().sum()

missing_values

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
Coupon_code       0
Customer_ID       0
dtype: int64

## Step 4 Bulk Loaded

#### Generate A second open data source of your choice

(product catalogue, city look-ups, coupon descriptions, etc.)

##### Check for the unique items in the previous file

In [9]:
items = sales_df['Item Type'].unique()

items

array(['Cosmetics', 'Vegetables', 'Baby Food', 'Cereal', 'Fruits',
       'Clothes', 'Snacks', 'Household', 'Office Supplies', 'Beverages',
       'Personal Care', 'Meat'], dtype=object)

In [10]:
cntry = sales_df['Country'].unique()
# print(cntry)

In [11]:
regions = sales_df['Region'].unique()
# print(regions)

In [12]:
# secondary data set
from synthetic_data_generate import SyntheticSalesData

sec_generator = SyntheticSalesData(region=regions, country=cntry, count=500)

methods = [method for method in dir(SyntheticSalesData) 
           if callable(getattr(SyntheticSalesData, method)) and not method.startswith("__")]

print("Methods in SyntheticData:", methods)

# secondary_sales_df = sec_data.generate_product_records()

Methods in SyntheticData: ['generate_city_lookup', 'generate_coupon_description', 'generate_full_records', 'generate_product', 'generate_product_records']

In [13]:
# Import your class
from synthetic_data_generate import SyntheticSalesData

# Generate the DataFrame
synthetic_data = sec_generator.generate_product_records()

# Show first 5 rows
synthetic_data.head()

# Confirm number of rows
print("Total rows generated:", synthetic_data.shape[0])

synthetic_data.head(10)

Total rows generated: 500

,Coupon Description,Product,Region,Country,City,Postal Code
0,10% off on Office Supplies! Limited time offer.,Beverages,Central America and the Caribbean,Guinea,East Ryan,21764
1,Free Shipping off on Office Supplies! Limited ...,Beverages,Australia and Oceania,Albania,Robertsonview,52879
2,Buy 1 Get 1 off on Baby Food! Limited time offer.,Fruits,Sub-Saharan Africa,Tunisia,North Tiffanyview,18854
3,Buy 1 Get 1 off on Personal Care! Limited time...,Office Supplies,Middle East and North Africa,Mozambique,Port Jamesstad,61285
4,25% off on Personal Care! Limited time offer.,Snacks,Middle East and North Africa,Tanzania,South Jennifer,64041
5,Buy 1 Get 1 off on Cereal! Limited time offer.,Personal Care,North America,Democratic Republic of the Congo,West Dannyland,32324
6,Buy 1 Get 1 off on Vegetables! Limited time of...,Household,Central America and the Caribbean,Maldives,Thomasburgh,99575
7,25% off on Cereal! Limited time offer.,Office Supplies,Central America and the Caribbean,Kenya,Lauramouth,02041
8,10% off on Cosmetics! Limited time offer.,Cereal,North America,Liechtenstein,North Jeffrey,91035
9,Buy 1 Get 1 off on Meat! Limited time offer.,Cereal,Central America and the Caribbean,Liberia,Williamsland,46476

In [14]:
# # save the secondary data to a csv file
# synthetic_data.to_csv("../data/secondary_synthetic_data.csv")

# print("CSV File saved successfully!!")

In [15]:
# introduce some missing values
def introduce_missing_values(df, missing_rate=0.1):
    synthetic_data__copy = df.copy()
    total_cells = synthetic_data__copy.size
    num_missing = int(total_cells * missing_rate)

    for _ in range(num_missing):
        i = np.random.randint(0, synthetic_data__copy.shape[0])
        j = np.random.randint(0, synthetic_data__copy.shape[1])
        synthetic_data__copy.iat[i, j] = np.nan

    return synthetic_data__copy


synthetic_df_copy = introduce_missing_values(synthetic_data)

synthetic_df_copy

,Coupon Description,Product,Region,Country,City,Postal Code
0,NaN,Beverages,Central America and the Caribbean,Guinea,East Ryan,21764
1,Free Shipping off on Office Supplies! Limited ...,NaN,Australia and Oceania,Albania,Robertsonview,52879
2,Buy 1 Get 1 off on Baby Food! Limited time offer.,Fruits,Sub-Saharan Africa,Tunisia,North Tiffanyview,18854
3,Buy 1 Get 1 off on Personal Care! Limited time...,Office Supplies,NaN,Mozambique,Port Jamesstad,61285
4,25% off on Personal Care! Limited time offer.,Snacks,Middle East and North Africa,Tanzania,South Jennifer,64041
...,...,...,...,...,...,...
495,10% off on Household! Limited time offer.,Household,Australia and Oceania,Uzbekistan,NaN,77738
496,NaN,Meat,Middle East and North Africa,Afghanistan,Mclaughlinville,24667
497,25% off on Clothes! Limited time offer.,Cosmetics,NaN,Malta,Phillipberg,93387
498,Buy 1 Get 1 off on Fruits! Limited time offer.,Cereal,North America,South Sudan,West Jonathantown,08531
499,10% off on Household! Limited time offer.,Clothes,Middle East and North Africa,Romania,Nicholasport,43540

In [16]:
# save the secondary data to a csv file
synthetic_df_copy.to_csv("../data/synthetic_data.csv")

print("CSV File saved successfully of the data with missing values!!")

CSV File saved successfully of the data with missing values!!

 Check for missing values

In [17]:
# check for missing values
missing_values = synthetic_df_copy.isnull().sum()

missing_values

Coupon Description    56
Product               43
Region                40
Country               47
City                  55
Postal Code           45
dtype: int64

### Merge the secondary to the original.

In [18]:
# add  the city, coupun description and postal code to the original data file

# Select only the extra columns you want
synthetic_subset = synthetic_df_copy[["City", "Coupon Description", "Postal Code"]]

# Concatenate synthetic columns to your original sales data
merged_sales_df = pd.concat([sales_df.reset_index(drop=True), 
                                synthetic_subset.reset_index(drop=True)], axis=1)


merged_sales_df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Coupon_code,Customer_ID,City,Coupon Description,Postal Code
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02,9GVAC4W9I6XA82G,AX157377,East Ryan,NaN,21764
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34,LDOZZNQ0H63HALO,AX186432,Robertsonview,Free Shipping off on Office Supplies! Limited ...,52879
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62,71WUUHO4FEGOTT3,AX196913,North Tiffanyview,Buy 1 Get 1 off on Baby Food! Limited time offer.,18854
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98,B8IXDM1PVRRGQHH,AX199663,Port Jamesstad,Buy 1 Get 1 off on Personal Care! Limited time...,61285
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45,Q6F2E0ISEHTO91O,AX197093,South Jennifer,25% off on Personal Care! Limited time offer.,64041

In [19]:
# save the new csv 
merged_sales_df.to_csv("../data/merged_dataset.csv")

print("Successfully saved the Merged dataset")

Successfully saved the Merged dataset

### Add the data from csv to sql -- Neon

In [20]:
# renaming

# unit sold - quantity
#

## Step 5: Quick Profiling

In [21]:
merged_sales_df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,5.000000e+02,500.000000,500.000000,500.00000,5.000000e+02,5.000000e+02,5.000000e+02
mean,5.347198e+08,5132.034000,274.295060,194.96930,1.422384e+06,1.010532e+06,4.118521e+05
std,2.536945e+08,2891.092845,223.422871,182.07284,1.546266e+06,1.213409e+06,3.941445e+05
min,1.029280e+08,64.000000,9.330000,6.92000,2.556420e+03,1.896080e+03,6.603400e+02
25%,3.056570e+08,2498.250000,81.730000,56.67000,3.211046e+05,1.732599e+05,1.119925e+05
50%,5.494032e+08,5319.500000,205.700000,117.11000,8.228263e+05,4.977766e+05,2.906816e+05
75%,7.401887e+08,7637.250000,437.200000,364.69000,1.884634e+06,1.266353e+06,5.764853e+05
max,9.955298e+08,9958.000000,668.270000,524.96000,6.617210e+06,5.204978e+06,1.725486e+06

- Price

In [22]:
min_price = min(merged_sales_df['Unit Price'])
max_price = max(merged_sales_df['Unit Price'])
mean_price = (merged_sales_df['Unit Price']).mean()

print(f"The maximum price is : {max_price}\nThe minimum price is: {min_price}\nThe mean price for the items is: {mean_price}")

The maximum price is : 668.27
The minimum price is: 9.33
The mean price for the items is: 274.29506

- Unique city count (set)

In [23]:
# print("Missing cities:", merged_sales_df['City'].isnull().sum())

In [24]:
unique_cities = set(merged_sales_df['City'].unique())

print("The number of unque cities:", len(unique_cities))

The number of unque cities: 438

## Step 6: Spot a Grime

In [25]:
merged_sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              500 non-null    object
 1   Country             500 non-null    object
 2   Item Type           500 non-null    object
 3   Sales Channel       500 non-null    object
 4   Order Priority      500 non-null    object
 5   Order Date          500 non-null    object
 6   Order ID            500 non-null    int64
 7   Ship Date           500 non-null    object
 8   Units Sold          500 non-null    int64
 9   Unit Price          500 non-null    float64
 10  Unit Cost           500 non-null    float64
 11  Total Revenue       500 non-null    float64
 12  Total Cost          500 non-null    float64
 13  Total Profit        500 non-null    float64
 14  Coupon_code         500 non-null    object
 15  Customer_ID         500 non-null    object
 16  City                445 non-null    object
 17  Coupon Description  444 non-null    object
 18  Postal Code         455 non-null    object
dtypes: float64(5), int64(2), object(12)
memory usage: 74.3+ KB

In [26]:
# Identify at least three dirty data cases

duplicates = merged_sales_df.duplicated()

duplicates.sum()

np.int64(0)

In [27]:
missing_values = merged_sales_df.isnull().sum()

missing_values

Region                 0
Country                0
Item Type              0
Sales Channel          0
Order Priority         0
Order Date             0
Order ID               0
Ship Date              0
Units Sold             0
Unit Price             0
Unit Cost              0
Total Revenue          0
Total Cost             0
Total Profit           0
Coupon_code            0
Customer_ID            0
City                  55
Coupon Description    56
Postal Code           45
dtype: int64

In [28]:
# look for wrong data
merged_sales_df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Coupon_code,Customer_ID,City,Coupon Description,Postal Code
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02,9GVAC4W9I6XA82G,AX157377,East Ryan,NaN,21764
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34,LDOZZNQ0H63HALO,AX186432,Robertsonview,Free Shipping off on Office Supplies! Limited ...,52879
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62,71WUUHO4FEGOTT3,AX196913,North Tiffanyview,Buy 1 Get 1 off on Baby Food! Limited time offer.,18854
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98,B8IXDM1PVRRGQHH,AX199663,Port Jamesstad,Buy 1 Get 1 off on Personal Care! Limited time...,61285
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45,Q6F2E0ISEHTO91O,AX197093,South Jennifer,25% off on Personal Care! Limited time offer.,64041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Middle East and North Africa,Algeria,Meat,Offline,M,9/2/2011,183022201,10/15/2011,9191,421.89,364.69,3877590.99,3351865.79,525725.20,TC25OYBR0MIZBA3,AX108318,NaN,10% off on Household! Limited time offer.,77738
496,Europe,Italy,Personal Care,Online,L,3/21/2011,127589738,4/2/2011,5494,81.73,56.67,449024.62,311344.98,137679.64,5ESDZ9N6YG53KHJ,AX116767,Mclaughlinville,NaN,24667
497,Europe,Russia,Fruits,Offline,L,1/8/2011,221530139,1/26/2011,4546,9.33,6.92,42414.18,31458.32,10955.86,NX5ZN9OOWS0F321,AX167563,Phillipberg,25% off on Clothes! Limited time offer.,93387
498,Central America and the Caribbean,Antigua and Barbuda,Office Supplies,Offline,M,2/22/2015,363329732,2/22/2015,6197,651.21,524.96,4035548.37,3253177.12,782371.25,CTGJEKDFI5S3WL4,AX124498,West Jonathantown,Buy 1 Get 1 off on Fruits! Limited time offer.,08531
499,Middle East and North Africa,Jordan,Fruits,Online,C,5/15/2017,521787345,6/25/2017,7325,9.33,6.92,68342.25,50689.00,17653.25,FLZXRS0WID8B8DY,AX143364,Nicholasport,10% off on Household! Limited time offer.,43540

## Step 7 Cleaning Rules

In [37]:
# define a function that does the cleaning
column_rename = {
    "Unit Sold": "Quantity",
    
}
def clean_df(df, rename_map=column_rename):
    """
    Clean the merged_df DataFrame by:
    1. Removing duplicate rows
    2. Renaming columns
    3. Dropping rows with missing values
    """
    # Step 1: Remove duplicate rows
    df_cleaned = df.drop_duplicates()

    # Step 2: Rename columns if a mapping is provided
    if rename_map:
        df_cleaned = df_cleaned.rename(columns=rename_map)

    # Step 3: Drop rows with any missing values
    merged_df_cleaned = df_cleaned.dropna()

    return merged_df_cleaned
    
cleaned_df = clean_df(merged_sales_df)

In [38]:
# clean df
cleaned_df.isnull().sum()

Region                0
Country               0
Item Type             0
Sales Channel         0
Order Priority        0
Order Date            0
Order ID              0
Ship Date             0
Units Sold            0
Unit Price            0
Unit Cost             0
Total Revenue         0
Total Cost            0
Total Profit          0
Coupon_code           0
Customer_ID           0
City                  0
Coupon Description    0
Postal Code           0
dtype: int64

## Step 8 : Transformations

In [39]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 361 entries, 1 to 499
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              361 non-null    object
 1   Country             361 non-null    object
 2   Item Type           361 non-null    object
 3   Sales Channel       361 non-null    object
 4   Order Priority      361 non-null    object
 5   Order Date          361 non-null    object
 6   Order ID            361 non-null    int64
 7   Ship Date           361 non-null    object
 8   Units Sold          361 non-null    int64
 9   Unit Price          361 non-null    float64
 10  Unit Cost           361 non-null    float64
 11  Total Revenue       361 non-null    float64
 12  Total Cost          361 non-null    float64
 13  Total Profit        361 non-null    float64
 14  Coupon_code         361 non-null    object
 15  Customer_ID         361 non-null    object
 16  City                361 non-null    object
 17  Coupon Description  361 non-null    object
 18  Postal Code         361 non-null    object
dtypes: float64(5), int64(2), object(12)
memory usage: 56.4+ KB

In [41]:
# convert date columns to the right type
date_columns = ["Order Date", "Ship Date"]

for col in date_columns:
    cleaned_df[col] = pd.to_datetime(cleaned_df[col], errors='coerce')
    

cleaned_df.info()

cleaned_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 361 entries, 1 to 499
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              361 non-null    object
 1   Country             361 non-null    object
 2   Item Type           361 non-null    object
 3   Sales Channel       361 non-null    object
 4   Order Priority      361 non-null    object
 5   Order Date          361 non-null    datetime64[ns]
 6   Order ID            361 non-null    int64
 7   Ship Date           361 non-null    datetime64[ns]
 8   Units Sold          361 non-null    int64
 9   Unit Price          361 non-null    float64
 10  Unit Cost           361 non-null    float64
 11  Total Revenue       361 non-null    float64
 12  Total Cost          361 non-null    float64
 13  Total Profit        361 non-null    float64
 14  Coupon_code         361 non-null    object
 15  Customer_ID         361 non-null    object
 16  City                361 non-null    object
 17  Coupon Description  361 non-null    object
 18  Postal Code         361 non-null    object
dtypes: datetime64[ns](2), float64(5), int64(2), object(10)
memory usage: 56.4+ KB

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Coupon_code,Customer_ID,City,Coupon Description,Postal Code
1,North America,Canada,Vegetables,Online,M,2011-11-07,185941302,2011-12-08,3018,154.06,90.93,464953.08,274426.74,190526.34,LDOZZNQ0H63HALO,AX186432,Robertsonview,Free Shipping off on Office Supplies! Limited ...,52879
2,Middle East and North Africa,Libya,Baby Food,Offline,C,2016-10-31,246222341,2016-12-09,1517,255.28,159.42,387259.76,241840.14,145419.62,71WUUHO4FEGOTT3,AX196913,North Tiffanyview,Buy 1 Get 1 off on Baby Food! Limited time offer.,18854
3,Asia,Japan,Cereal,Offline,C,2010-04-10,161442649,2010-05-12,3322,205.70,117.11,683335.40,389039.42,294295.98,B8IXDM1PVRRGQHH,AX199663,Port Jamesstad,Buy 1 Get 1 off on Personal Care! Limited time...,61285
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,2011-08-16,645713555,2011-08-31,9845,9.33,6.92,91853.85,68127.40,23726.45,Q6F2E0ISEHTO91O,AX197093,South Jennifer,25% off on Personal Care! Limited time offer.,64041
5,Europe,Armenia,Cereal,Online,H,2014-11-24,683458888,2014-12-28,9528,205.70,117.11,1959909.60,1115824.08,844085.52,TS2THBNJ1K9JT6G,AX194077,West Dannyland,Buy 1 Get 1 off on Cereal! Limited time offer.,32324

In [42]:
# transform my postal code to numeric

cleaned_df['Postal Code'] = pd.to_numeric(cleaned_df['Postal Code'], errors='coerce')

cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 361 entries, 1 to 499
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              361 non-null    object
 1   Country             361 non-null    object
 2   Item Type           361 non-null    object
 3   Sales Channel       361 non-null    object
 4   Order Priority      361 non-null    object
 5   Order Date          361 non-null    datetime64[ns]
 6   Order ID            361 non-null    int64
 7   Ship Date           361 non-null    datetime64[ns]
 8   Units Sold          361 non-null    int64
 9   Unit Price          361 non-null    float64
 10  Unit Cost           361 non-null    float64
 11  Total Revenue       361 non-null    float64
 12  Total Cost          361 non-null    float64
 13  Total Profit        361 non-null    float64
 14  Coupon_code         361 non-null    object
 15  Customer_ID         361 non-null    object
 16  City                361 non-null    object
 17  Coupon Description  361 non-null    object
 18  Postal Code         361 non-null    int64
dtypes: datetime64[ns](2), float64(5), int64(3), object(9)
memory usage: 56.4+ KB

## Step 9 Feature Engineering

In [ ]:
# add wait time in days from when the user orders to when it is shipped in days

cleaned_df["Wait Time"] = (cleaned_df["Ship Date"] - cleaned_df["Order Date"]).dt.days

cleaned_df["Wait Time"]

1      31
2      39
3      32
4      15
5      34
       ..
493    31
494    29
497    18
498     0
499    41
Name: Wait Time, Length: 361, dtype: int64

## Step 10 Mini- Aggregation

In [ ]:
# group the item type by wait time 
# - shows how many items of each type fall under each wait time

group1 = cleaned_df.groupby('Wait Time')['Item Type'].value_counts()
print(group1)

Wait Time  Item Type
0          Baby Food          2
           Office Supplies    2
           Beverages          1
           Fruits             1
           Meat               1
                             ..
49         Household          1
           Meat               1
50         Snacks             2
           Beverages          1
           Meat               1
Name: count, Length: 276, dtype: int64

In [51]:
# group mean revenue by sales channel

group2 = cleaned_df.groupby('Sales Channel')['Total Revenue'].mean()
group2

Sales Channel
Offline    1.303984e+06
Online     1.421767e+06
Name: Total Revenue, dtype: float64

In [ ]:
# group iten type by country and revenue

group3 = cleaned_df.groupby(['Item Type', 'Country'])['Total Revenue'].mean().unstack()
group3

Country,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Armenia,Austria,Bahrain,Bangladesh,...,Ukraine,United Arab Emirates,United Kingdom,United States of America,Uzbekistan,Vanuatu,Vatican City,Vietnam,Yemen,Zimbabwe
Item Type,,,,,,,,,,,,,,,,,,,,,
Baby Food,20422.4,NaN,NaN,1782364.96,NaN,NaN,NaN,NaN,NaN,1948296.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1172756.32,1446927.04,NaN
Beverages,NaN,NaN,NaN,28470.00,33120.1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,86121.75,NaN,NaN,NaN,NaN,NaN,NaN
Cereal,1456561.7,NaN,NaN,NaN,872168.0,NaN,1959909.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,915776.40,NaN,NaN,NaN,NaN,NaN
Clothes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,611968.00,416575.36,NaN,808453.44,187743.04,NaN,NaN,NaN,NaN,NaN
Cosmetics,NaN,NaN,NaN,NaN,3005312.8,NaN,NaN,NaN,NaN,NaN,...,3658489.60,NaN,NaN,NaN,NaN,NaN,NaN,2791084.80,NaN,NaN
Fruits,NaN,19630.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71159.91
Household,NaN,NaN,NaN,429029.34,NaN,NaN,NaN,NaN,NaN,NaN,...,858726.95,NaN,1522319.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Meat,NaN,NaN,NaN,NaN,NaN,NaN,3753133.44,NaN,NaN,NaN,...,NaN,NaN,NaN,2807256.06,NaN,NaN,NaN,NaN,NaN,2139826.08
Office Supplies,NaN,4488139.32,NaN,NaN,NaN,4035548.37,NaN,3613130.15,3577747.74,NaN,...,931881.51,NaN,1855948.50,6021738.87,NaN,NaN,NaN,2737035.63,1415079.33,NaN
Personal Care,NaN,NaN,NaN,NaN,NaN,NaN,678277.27,NaN,NaN,505091.40,...,579629.16,NaN,NaN,NaN,812559.66,NaN,NaN,NaN,NaN,NaN
Snacks,NaN,NaN,NaN,NaN,NaN,NaN,712243.44,NaN,NaN,NaN,...,NaN,248552.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vegetables,NaN,1233404.36,1083966.16,NaN,NaN,NaN,NaN,466801.80,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1487295.24,334772.38,NaN,NaN,492221.70

In [57]:
# save to a dictionary the revenue of each country
revenue_by_country = cleaned_df.groupby('Country')['Total Revenue'].sum().to_dict()

revenue_by_country

{'Afghanistan': 1476984.0999999999,
 'Albania': 5741174.0,
 'Algeria': 1083966.16,
 'Andorra': 2239864.3,
 'Angola': 3910600.9,
 'Antigua and Barbuda ': 4035548.37,
 'Armenia': 7103563.75,
 'Austria': 11306192.25,
 'Bahrain': 3577747.74,
 'Bangladesh': 2958479.76,
 'Barbados': 91090.26,
 'Belarus': 5395855.5,
 'Belgium': 4225611.36,
 'Benin': 2036078.19,
 'Bhutan': 527713.12,
 'Bulgaria': 2739002.8600000003,
 'Burkina Faso': 1320471.27,
 'Burundi': 4475883.8,
 'Canada': 1119245.9,
 'Cape Verde': 1137180.5,
 'Central African Republic': 3456417.21,
 'Chad': 11828683.05,
 'China': 1425940.28,
 'Costa Rica': 5565891.87,
 "Cote d'Ivoire": 588129.08,
 'Croatia': 879495.94,
 'Cuba': 6283811.57,
 'Cyprus': 4890570.390000001,
 'Czech Republic': 8621422.54,
 'Democratic Republic of the Congo': 2854597.32,
 'Denmark': 260832.65,
 'Dominican Republic': 5150884.64,
 'East Timor': 714376.22,
 'Egypt': 424867.3,
 'El Salvador': 1582362.8099999998,
 'Equatorial Guinea': 5067593.53,
 'Eritrea': 1474455.62,
 'Estonia': 6356825.8100000005,
 'Ethiopia': 242247.72,
 'Federated States of Micronesia': 409058.65,
 'Fiji': 1383075.3,
 'Finland': 1471298.3199999998,
 'Gabon': 5189106.16,
 'Georgia': 5353296.59,
 'Germany': 7413459.050000001,
 'Ghana': 2349641.06,
 'Greece': 4131876.1300000004,
 'Greenland': 6950827.7,
 'Grenada': 1958153.5,
 'Guatemala': 456184.3,
 'Guinea': 6129672.33,
 'Guinea-Bissau': 2276687.9,
 'Honduras': 1112631.3,
 'Hungary': 6512861.89,
 'Iceland': 1567469.8,
 'India': 4421455.26,
 'Indonesia': 540816.4,
 'Iran': 2305843.54,
 'Iraq': 4140995.33,
 'Ireland': 5599555.46,
 'Israel': 612340.9199999999,
 'Italy': 1384978.1,
 'Japan': 6766832.07,
 'Jordan': 2190632.5999999996,
 'Kazakhstan': 312885.3,
 'Kenya': 983572.73,
 'Kiribati': 1831763.01,
 'Kyrgyzstan': 12007.71,
 'Laos': 147427.15,
 'Lebanon': 6843671.85,
 'Lesotho': 4017965.7,
 'Liberia': 53899.409999999996,
 'Libya': 2191624.96,
 'Liechtenstein': 1676249.3,
 'Lithuania': 100642.70999999999,
 'Luxembourg': 8381146.5,
 'Macedonia': 1657236.29,
 'Madagascar': 71747.7,
 'Malawi': 4746596.3,
 'Malaysia': 5056817.6899999995,
 'Maldives': 652140.8999999999,
 'Mali': 2461820.8,
 'Malta': 3731064.8,
 'Marshall Islands': 1539931.51,
 'Mauritania': 3837977.93,
 'Mauritius ': 2416195.12,
 'Moldova ': 7233605.42,
 'Monaco': 673088.14,
 'Mongolia': 2793093.42,
 'Montenegro': 1683391.5899999999,
 'Morocco': 5907919.53,
 'Mozambique': 8522101.36,
 'Myanmar': 2478319.86,
 'Namibia': 153595.65,
 'Nauru': 1151598.5,
 'Nepal': 1281162.96,
 'New Zealand': 6533529.539999999,
 'Nicaragua': 1411643.94,
 'Niger': 3309960.48,
 'Nigeria': 131748.76,
 'North Korea': 25480.86,
 'Norway': 435289.76,
 'Oman': 713921.82,
 'Pakistan': 1164409.9500000002,
 'Palau': 1213578.32,
 'Panama': 3445573.2,
 'Papua New Guinea': 9578012.93,
 'Philippines': 1782012.8199999998,
 'Poland': 768922.01,
 'Portugal': 11930167.2,
 'Qatar': 1651130.65,
 'Republic of the Congo': 3374972.3099999996,
 'Romania': 3493687.38,
 'Russia': 2114300.23,
 'Rwanda': 3027371.79,
 'Saint Kitts and Nevis ': 2761799.33,
 'Saint Lucia': 1721549.67,
 'Samoa ': 76386.72,
 'Saudi Arabia': 1143433.32,
 'Senegal': 6402527.33,
 'Serbia': 3617830.0,
 'Seychelles ': 762803.62,
 'Slovakia': 1415960.94,
 'Slovenia': 387239.45,
 'Solomon Islands': 1892859.3,
 'Somalia': 2373912.0999999996,
 'South Africa': 7415374.68,
 'South Korea': 1145224.88,
 'South Sudan': 2718150.54,
 'Sudan': 4440158.68,
 'Swaziland': 4592291.67,
 'Sweden': 4190665.69,
 'Switzerland': 2493757.99,
 'Syria': 5002000.95,
 'Taiwan': 1094199.58,
 'Tajikistan': 3119636.4699999997,
 'Tanzania': 1027516.9299999999,
 'Thailand': 1279618.35,
 'The Bahamas': 4536550.54,
 'Togo': 1734332.62,
 'Tonga': 11310770.93,
 'Trinidad and Tobago': 929968.44,
 'Tunisia ': 5889847.2700000005,
 'Turkey': 5921193.97,
 'Tuvalu': 319044.78,
 'Uganda': 1425452.98,
 'Ukraine': 6640695.22,
 'United Arab Emirates': 665128.1799999999,
 'United Kingdom': 3378267.56,
 'United States of America': 9723570.120000001,
 'Uzbekistan': 1916079.1,
 'Vanuatu': 1487295.24,
 'Vatican City': 334772.38,
 'Vietnam': 9437912.38,
 'Yemen': 2862006.37,
 'Zimbabwe': 4843033.77}

## Step 11: Serialization Checkpoint

In [58]:
# save the cleaned data to json
cleaned_df.to_json('../data/cleaned_data.json', orient='records', lines=True)

print("The cleaned dataframe is saved to json file sucessfully!")

The cleaned dataframe is saved to json file sucessfully!

## Step 12: Soft Interview Reflection

Functions have steamlined my workflow by encapsulating repetive tasks into clean, reusable code. They have helped me with the generation of synthetic data, data cleaning, transformation and analysis steps, such as removing duplicates, conversion of dates. This has made my code easier to maintain and scale. With functions, i have been able to focus on the logic and structure across the datasets i have used.

In [60]:
cleaned_df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit',
       'Coupon_code', 'Customer_ID', 'City', 'Coupon Description',
       'Postal Code', 'Wait Time'],
      dtype='object')

In [61]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 361 entries, 1 to 499
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              361 non-null    object
 1   Country             361 non-null    object
 2   Item Type           361 non-null    object
 3   Sales Channel       361 non-null    object
 4   Order Priority      361 non-null    object
 5   Order Date          361 non-null    datetime64[ns]
 6   Order ID            361 non-null    int64
 7   Ship Date           361 non-null    datetime64[ns]
 8   Units Sold          361 non-null    int64
 9   Unit Price          361 non-null    float64
 10  Unit Cost           361 non-null    float64
 11  Total Revenue       361 non-null    float64
 12  Total Cost          361 non-null    float64
 13  Total Profit        361 non-null    float64
 14  Coupon_code         361 non-null    object
 15  Customer_ID         361 non-null    object
 16  City                361 non-null    object
 17  Coupon Description  361 non-null    object
 18  Postal Code         361 non-null    int64
 19  Wait Time           361 non-null    int64
dtypes: datetime64[ns](2), float64(5), int64(4), object(9)
memory usage: 67.3+ KB


### 📋 Field Definitions Table

| Field              | Type           | Description                          | Source        |
|--------------------|----------------|--------------------------------------|---------------|
| Region             | string         | Region where the order was placed    | Primary CSV   |
| Country            | string         | Country where the order was placed   | Primary CSV   |
| Item Type          | string         | Category of item purchased           | Primary CSV   |
| Sales Channel      | string         | Means by whci order was placed       | Primary CSV   |
| Order Priority     | string         | Importance of the order              | Primary CSV   |
| Order Date         | datetime       | Date when the order was placed       | Primary CSV   |
| Order ID           | integer        | Unique order identifier              | Primary CSV   |
| Ship Date          | datetime       | Date when the order was shipped      | Primary CSV   |
| Units Sold         | integer        | Quantity f items                     | Primary CSV   |
| Unit Price         | float          | Price of single item                 | Primary CSV   |
| Unit Cost          | float          | Cost of the item                     | Primary CSV   |
| Total Revenue      | float          | Total revenue from the order         | Primary CSV   |
| Total Cost         | float          | Total cost of the items ordered      | Primary CSV   |
| Total Profit       | float          | Total profit from the order          | Primary CSV   |
| Coupon_code        | string         | Promotional code used for discount   | Synthetic     |
| Customer_ID        | string         | Unique customer identifier           | Synthetic     |
| City               | string         | City of the customer                 | Synthetic     |
| Coupon Description | string         | Information on the coupon            | Synthetic     |
| Postal Code        | integer        | Code of the customer                 | Synthetic     |
| Wait Time          | integer        | Days between order and ship date     | Derived       |

### 🛠️ Notes on Creation
- **Synthetic** fields like `Coupon Code`, `City`, and `Customer ID` were generated using tools like Faker to simulate realistic data.
    - The `Customer ID` was created by concatenating a fixed prefix with a randomly generated integer between 100000 and 200000
    - `City` and `Postal Code` use Faker to generate realistic but fictitious location data
    - `Coupon Description` is a formatted string combining a discount type and product name.
    - The `coupon code` is generated by randomly selecting uppercase letters and digits to form a string of a specified length, creating a unique alphanumeric promotional code

- **Derived** field `Wait Time` was derived from date subtraction.
- All types were standardized during cleaning, with dates converted to `datetime` and numeric fields cast to `float` or `integer`.